--
-- Created by IntelliJ IDEA.
-- User: cmouilleron
-- Date: 28/02/2017
-- Time: 21:41
-- To change this template use File | Settings | File Templates.
--

PI_COULOIR_SERVEUR_IP = TO_BE_DEFINED
PI_COULOIR_SERVEUR_LOGIN = TO_BE_DEFINED

PI_SALON_SERVEUR_IP = TO_BE_DEFINED
PI_SALON_SERVEUR_LOGIN = TO_BE_DEFINED

SONOFF_VMC_IP = TO_BE_DEFINED

-- TOKEN D'ACCESS AUX APIS EDF
EDF_TEMPO_TOKEN = TO_BE_DEFINED

-- TUYA CONFIGURATION
TUYA_CLIEND_ID = TO_BE_DEFINED
TUYA_CLIENT_SECRET = TO_BE_DEFINED
